/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sachin.deardominos.gui;

//import com.mysql.cj.Session;
//import com.mysql.cj.protocol.Message;
import com.sachin.deardominos.dao.LedgerDAO;
import com.sachin.deardominos.dao.ProductDAO;
import com.sachin.deardominos.pojo.Ledger;
import com.sachin.deardominos.pojo.Product;
//import com.sun.jdi.connect.Transport;
import java.awt.CardLayout;


import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;






/**
 *
 * @author Shyam sundar
 */
public class MainScreen extends javax.swing.JFrame {

    private static CharSequence email;

    /**
     * Creates new form MainScreen
     */
    private CardLayout cardLayout;
    private List<Product> cartData = new ArrayList<>();
    private int cartCount = 0;
    private double totalAmt = 0.0;
    public MainScreen() {
        initComponents();
        
        cardLayout = (CardLayout) (cardPanel.getLayout());
        cardLayout.show(cardPanel, "cardAdmin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        Admin = new javax.swing.JPanel();
        btnPlaceOrder = new javax.swing.JLabel();
        btnOrderHistory = new javax.swing.JLabel();
        bgAdmin = new javax.swing.JLabel();
        ledger = new javax.swing.JPanel();
        btnBackLedger = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLedger = new javax.swing.JTable();
        bgLedger = new javax.swing.JLabel();
        menuHome = new javax.swing.JPanel();
        btnBackMenuHome = new javax.swing.JLabel();
        btnViewAllVegpizza = new javax.swing.JLabel();
        btnViewAllNonVegPizza = new javax.swing.JLabel();
        btnViewPizzaMania = new javax.swing.JLabel();
        btnAllBeverages = new javax.swing.JLabel();
        btnMenuHomeCart = new javax.swing.JLabel();
        btnMenuHomeCartCount = new javax.swing.JLabel();
        bgMenuHome = new javax.swing.JLabel();
        menuVeg = new javax.swing.JPanel();
        v01 = new javax.swing.JLabel();
        v02 = new javax.swing.JLabel();
        v03 = new javax.swing.JLabel();
        v04 = new javax.swing.JLabel();
        v05 = new javax.swing.JLabel();
        v06 = new javax.swing.JLabel();
        v07 = new javax.swing.JLabel();
        v08 = new javax.swing.JLabel();
        btnBackMenuVeg = new javax.swing.JLabel();
        btnMenuVegCart = new javax.swing.JLabel();
        btnMenuVegCartCount = new javax.swing.JLabel();
        bgMenuVeg = new javax.swing.JLabel();
        menuNonVeg = new javax.swing.JPanel();
        nv01 = new javax.swing.JLabel();
        nv02 = new javax.swing.JLabel();
        nv03 = new javax.swing.JLabel();
        nv04 = new javax.swing.JLabel();
        nv05 = new javax.swing.JLabel();
        nv06 = new javax.swing.JLabel();
        nv07 = new javax.swing.JLabel();
        nv08 = new javax.swing.JLabel();
        btnBackMenuNonVeg = new javax.swing.JLabel();
        btnMenuNonVegCart = new javax.swing.JLabel();
        btnMenNonVegCartCount = new javax.swing.JLabel();
        bgMenuNonVeg = new javax.swing.JLabel();
        menuManiaVeg = new javax.swing.JPanel();
        mv01 = new javax.swing.JLabel();
        mv02 = new javax.swing.JLabel();
        mv03 = new javax.swing.JLabel();
        mv04 = new javax.swing.JLabel();
        mv05 = new javax.swing.JLabel();
        mv06 = new javax.swing.JLabel();
        mv07 = new javax.swing.JLabel();
        mv08 = new javax.swing.JLabel();
        btnMenuManiaVegPressed = new javax.swing.JLabel();
        btnMenuManiaNonVeg = new javax.swing.JLabel();
        btnBackMenuManiaVeg = new javax.swing.JLabel();
        btnMenuManiaVegCart = new javax.swing.JLabel();
        btnMenuManiaVegCartCount = new javax.swing.JLabel();
        bgMenuManiaVeg = new javax.swing.JLabel();
        menuManiaNonVeg = new javax.swing.JPanel();
        btnBackMenuManiaNonVeg = new javax.swing.JLabel();
        btnMenuManiaVeg = new javax.swing.JLabel();
        btnMenuManiaNonVegPressed = new javax.swing.JLabel();
        mnv01 = new javax.swing.JLabel();
        mnv02 = new javax.swing.JLabel();
        mnv03 = new javax.swing.JLabel();
        btnMenuManiaNonVegCart = new javax.swing.JLabel();
        btnMenuManiaNonVegCartCount = new javax.swing.JLabel();
        bgMenuManiaNonVeg = new javax.swing.JLabel();
        menuBeverages = new javax.swing.JPanel();
        btnBackMenuBeverages = new javax.swing.JLabel();
        b01 = new javax.swing.JLabel();
        b02 = new javax.swing.JLabel();
        b03 = new javax.swing.JLabel();
        b04 = new javax.swing.JLabel();
        b05 = new javax.swing.JLabel();
        b06 = new javax.swing.JLabel();
        b07 = new javax.swing.JLabel();
        btnMenuBeverageCart = new javax.swing.JLabel();
        btnMenuBeverageCartCount = new javax.swing.JLabel();
        bgMenuBeverages = new javax.swing.JLabel();
        cart = new javax.swing.JPanel();
        btnBackCart = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCart = new javax.swing.JTable();
        lblCartTotal = new javax.swing.JLabel();
        btnRemove = new javax.swing.JLabel();
        btnproceed = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bgCart = new javax.swing.JLabel();
        payment = new javax.swing.JPanel();
        btnBackPayment = new javax.swing.JLabel();
        lblOrderNumber = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblPaymentTotal = new javax.swing.JLabel();
        lblGST = new javax.swing.JLabel();
        lblAmountPayable = new javax.swing.JLabel();
        btnSendReceipt = new javax.swing.JLabel();
        bgCart1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        cardPanel.setLayout(new java.awt.CardLayout());

        Admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnPlaceOrder.png"))); // NOI18N
        btnPlaceOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlaceOrderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlaceOrderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPlaceOrderMouseReleased(evt);
            }
        });
        Admin.add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 330, 70));

        btnOrderHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnOrderHistory.png"))); // NOI18N
        btnOrderHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrderHistoryMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOrderHistoryMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOrderHistoryMouseReleased(evt);
            }
        });
        Admin.add(btnOrderHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 330, 70));

        bgAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin.png"))); // NOI18N
        Admin.add(bgAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        cardPanel.add(Admin, "cardAdmin");
        Admin.getAccessibleContext().setAccessibleName("");

        ledger.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackLedger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackLedger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackLedgerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackLedgerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackLedgerMouseReleased(evt);
            }
        });
        ledger.add(btnBackLedger, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        tableLedger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "E-MAIL", "AMOUNT", "DATA", "TIME"
            }
        ));
        jScrollPane1.setViewportView(tableLedger);

        ledger.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 660, -1));

        bgLedger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ledger.png"))); // NOI18N
        ledger.add(bgLedger, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -70, -1, 880));

        cardPanel.add(ledger, "cardLedger");

        menuHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMenuHomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMenuHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackMenuHomeMouseReleased(evt);
            }
        });
        menuHome.add(btnBackMenuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnViewAllVegpizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnViewAll.png"))); // NOI18N
        btnViewAllVegpizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllVegpizzaMouseClicked(evt);
            }
        });
        menuHome.add(btnViewAllVegpizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 120, 40));

        btnViewAllNonVegPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnViewAll.png"))); // NOI18N
        btnViewAllNonVegPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllNonVegPizzaMouseClicked(evt);
            }
        });
        menuHome.add(btnViewAllNonVegPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        btnViewPizzaMania.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnViewAll.png"))); // NOI18N
        btnViewPizzaMania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewPizzaManiaMouseClicked(evt);
            }
        });
        menuHome.add(btnViewPizzaMania, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, -1, 40));

        btnAllBeverages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnViewAll.png"))); // NOI18N
        btnAllBeverages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAllBeveragesMouseClicked(evt);
            }
        });
        menuHome.add(btnAllBeverages, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 660, -1, 40));

        btnMenuHomeCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        btnMenuHomeCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuHomeCartMouseClicked(evt);
            }
        });
        menuHome.add(btnMenuHomeCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 20, 30));

        btnMenuHomeCartCount.setBackground(new java.awt.Color(230, 26, 57));
        btnMenuHomeCartCount.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btnMenuHomeCartCount.setForeground(new java.awt.Color(230, 26, 57));
        btnMenuHomeCartCount.setText("0");
        menuHome.add(btnMenuHomeCartCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, 30));

        bgMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuHome.png"))); // NOI18N
        menuHome.add(bgMenuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 770));

        cardPanel.add(menuHome, "cardMenuHome");

        menuVeg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v01MouseClicked(evt);
            }
        });
        v01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                v01KeyPressed(evt);
            }
        });
        menuVeg.add(v01, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 90, 40));

        v02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v02MouseClicked(evt);
            }
        });
        menuVeg.add(v02, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 90, -1));

        v03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v03MouseClicked(evt);
            }
        });
        menuVeg.add(v03, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 90, 40));

        v04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v04MouseClicked(evt);
            }
        });
        menuVeg.add(v04, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, 90, 40));

        v05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v05MouseClicked(evt);
            }
        });
        menuVeg.add(v05, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 90, 40));

        v06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v06MouseClicked(evt);
            }
        });
        menuVeg.add(v06, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 90, 40));

        v07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v07MouseClicked(evt);
            }
        });
        menuVeg.add(v07, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 90, 40));

        v08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        v08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v08MouseClicked(evt);
            }
        });
        menuVeg.add(v08, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 700, 90, 40));

        btnBackMenuVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackMenuVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMenuVegMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMenuVegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackMenuVegMouseReleased(evt);
            }
        });
        menuVeg.add(btnBackMenuVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        btnMenuVegCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        btnMenuVegCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuVegCartMouseClicked(evt);
            }
        });
        menuVeg.add(btnMenuVegCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 20, 30));

        btnMenuVegCartCount.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btnMenuVegCartCount.setForeground(new java.awt.Color(230, 26, 57));
        btnMenuVegCartCount.setText("0");
        menuVeg.add(btnMenuVegCartCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 20, 30));

        bgMenuVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuVeg.png"))); // NOI18N
        menuVeg.add(bgMenuVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        cardPanel.add(menuVeg, "cardMenuVeg");

        menuNonVeg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nv01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv01MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv01, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 90, 40));

        nv02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv02MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv02, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 90, -1));

        nv03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv03MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv03, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 90, -1));

        nv04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv04MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv04, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, 90, -1));

        nv05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv05MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv05, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, -1));

        nv06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv06MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv06, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 90, -1));

        nv07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv07MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv07, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 90, -1));

        nv08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        nv08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nv08MouseClicked(evt);
            }
        });
        menuNonVeg.add(nv08, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 700, 90, -1));

        btnBackMenuNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackMenuNonVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMenuNonVegMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMenuNonVegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackMenuNonVegMouseReleased(evt);
            }
        });
        menuNonVeg.add(btnBackMenuNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnMenuNonVegCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        btnMenuNonVegCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuNonVegCartMouseClicked(evt);
            }
        });
        btnMenuNonVegCart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMenuNonVegCartKeyPressed(evt);
            }
        });
        menuNonVeg.add(btnMenuNonVegCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 20, 30));

        btnMenNonVegCartCount.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btnMenNonVegCartCount.setForeground(new java.awt.Color(230, 26, 57));
        btnMenNonVegCartCount.setText("0");
        menuNonVeg.add(btnMenNonVegCartCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, 30));

        bgMenuNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuNonVeg.png"))); // NOI18N
        menuNonVeg.add(bgMenuNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        cardPanel.add(menuNonVeg, "cardMenuNonVeg");

        menuManiaVeg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mv01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv01MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv01, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        mv02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv02MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv02, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        mv03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv03MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv03, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, -1, -1));

        mv04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv04MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv04, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 680, -1, -1));

        mv05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv05MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv05, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, -1));

        mv06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv06MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv06, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, -1, -1));

        mv07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv07MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv07, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, -1, -1));

        mv08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mv08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mv08MouseClicked(evt);
            }
        });
        menuManiaVeg.add(mv08, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 700, -1, -1));

        btnMenuManiaVegPressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaVegPressed.png"))); // NOI18N
        menuManiaVeg.add(btnMenuManiaVegPressed, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        btnMenuManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaNonVeg.png"))); // NOI18N
        btnMenuManiaNonVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuManiaNonVegMouseClicked(evt);
            }
        });
        menuManiaVeg.add(btnMenuManiaNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        btnBackMenuManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackMenuManiaVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMenuManiaVegMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMenuManiaVegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackMenuManiaVegMouseReleased(evt);
            }
        });
        menuManiaVeg.add(btnBackMenuManiaVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        btnMenuManiaVegCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        btnMenuManiaVegCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuManiaVegCartMouseClicked(evt);
            }
        });
        menuManiaVeg.add(btnMenuManiaVegCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        btnMenuManiaVegCartCount.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btnMenuManiaVegCartCount.setForeground(new java.awt.Color(230, 26, 57));
        btnMenuManiaVegCartCount.setText("0");
        menuManiaVeg.add(btnMenuManiaVegCartCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        bgMenuManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuManiaVeg.png"))); // NOI18N
        menuManiaVeg.add(bgMenuManiaVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        cardPanel.add(menuManiaVeg, "cardMenuManiaVeg");

        menuManiaNonVeg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackMenuManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackMenuManiaNonVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMenuManiaNonVegMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMenuManiaNonVegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackMenuManiaNonVegMouseReleased(evt);
            }
        });
        menuManiaNonVeg.add(btnBackMenuManiaNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        btnMenuManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaVeg.png"))); // NOI18N
        btnMenuManiaVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuManiaVegMouseClicked(evt);
            }
        });
        menuManiaNonVeg.add(btnMenuManiaVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        btnMenuManiaNonVegPressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaNonVegPressed.png"))); // NOI18N
        menuManiaNonVeg.add(btnMenuManiaNonVegPressed, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        mnv01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mnv01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnv01MouseClicked(evt);
            }
        });
        menuManiaNonVeg.add(mnv01, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        mnv02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mnv02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnv02MouseClicked(evt);
            }
        });
        menuManiaNonVeg.add(mnv02, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        mnv03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        mnv03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnv03MouseClicked(evt);
            }
        });
        menuManiaNonVeg.add(mnv03, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        btnMenuManiaNonVegCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        btnMenuManiaNonVegCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuManiaNonVegCartMouseClicked(evt);
            }
        });
        menuManiaNonVeg.add(btnMenuManiaNonVegCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, -1));

        btnMenuManiaNonVegCartCount.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btnMenuManiaNonVegCartCount.setForeground(new java.awt.Color(230, 26, 57));
        btnMenuManiaNonVegCartCount.setText("0");
        menuManiaNonVeg.add(btnMenuManiaNonVegCartCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 7, -1, 50));

        bgMenuManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuManiaNonVeg.png"))); // NOI18N
        menuManiaNonVeg.add(bgMenuManiaNonVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardPanel.add(menuManiaNonVeg, "cardMenuManiaNonVeg");

        menuBeverages.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackMenuBeverages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackMenuBeverages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMenuBeveragesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMenuBeveragesMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMenuBeveragesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackMenuBeveragesMouseReleased(evt);
            }
        });
        menuBeverages.add(btnBackMenuBeverages, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        b01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b01MouseClicked(evt);
            }
        });
        menuBeverages.add(b01, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        b02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b02MouseClicked(evt);
            }
        });
        menuBeverages.add(b02, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        b03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b03MouseClicked(evt);
            }
        });
        menuBeverages.add(b03, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, -1, -1));

        b04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b04MouseClicked(evt);
            }
        });
        menuBeverages.add(b04, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 660, -1, -1));

        b05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b05MouseClicked(evt);
            }
        });
        menuBeverages.add(b05, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        b06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b06MouseClicked(evt);
            }
        });
        menuBeverages.add(b06, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        b07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnAdd.png"))); // NOI18N
        b07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b07MouseClicked(evt);
            }
        });
        menuBeverages.add(b07, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        btnMenuBeverageCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBag.png"))); // NOI18N
        btnMenuBeverageCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuBeverageCartMouseClicked(evt);
            }
        });
        menuBeverages.add(btnMenuBeverageCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        btnMenuBeverageCartCount.setFont(new java.awt.Font("OCR A Extended", 0, 25)); // NOI18N
        btnMenuBeverageCartCount.setForeground(new java.awt.Color(230, 26, 57));
        btnMenuBeverageCartCount.setText("0");
        menuBeverages.add(btnMenuBeverageCartCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, 50));

        bgMenuBeverages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuBeverages.png"))); // NOI18N
        menuBeverages.add(bgMenuBeverages, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardPanel.add(menuBeverages, "cardMenuBeverages");

        cart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackCartMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackCartMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackCartMouseReleased(evt);
            }
        });
        cart.add(btnBackCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        tableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product", "Amount"
            }
        ));
        jScrollPane2.setViewportView(tableCart);

        cart.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 470, -1));

        lblCartTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cart.add(lblCartTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 640, 60, 20));

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnRemove.png"))); // NOI18N
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMouseClicked(evt);
            }
        });
        cart.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 580, -1, -1));

        btnproceed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnProceed.png"))); // NOI18N
        btnproceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnproceedMouseClicked(evt);
            }
        });
        cart.add(btnproceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, -1, -1));

        jLabel1.setText("jLabel1");
        cart.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 60, 30));

        bgCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart.png"))); // NOI18N
        cart.add(bgCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardPanel.add(cart, "cardCart");

        payment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png"))); // NOI18N
        btnBackPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackPaymentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackPaymentMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackPaymentMouseReleased(evt);
            }
        });
        payment.add(btnBackPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblOrderNumber.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblOrderNumber.setText("jLabel25");
        payment.add(lblOrderNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblDate.setText("jLabel25");
        payment.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, -1, -1));

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblTime.setText("jLabel25");
        payment.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        payment.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 210, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        payment.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 270, -1));

        lblPaymentTotal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblPaymentTotal.setText("jLabel25");
        payment.add(lblPaymentTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        lblGST.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblGST.setText("jLabel25");
        payment.add(lblGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, -1));

        lblAmountPayable.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblAmountPayable.setText("jLabel25");
        payment.add(lblAmountPayable, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, -1, -1));

        btnSendReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnSendReceipt.png"))); // NOI18N
        btnSendReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendReceiptMouseClicked(evt);
            }
        });
        payment.add(btnSendReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, -1, -1));

        bgCart1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        bgCart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/payment.png"))); // NOI18N
        payment.add(bgCart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardPanel.add(payment, "cardPayment");

        getContentPane().add(cardPanel, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlaceOrderMousePressed
       btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnPlaceOrderPressed.png")));
    }//GEN-LAST:event_btnPlaceOrderMousePressed

    private void btnPlaceOrderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlaceOrderMouseReleased
        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnPlaceOrder.png")));
    }//GEN-LAST:event_btnPlaceOrderMouseReleased

    private void btnOrderHistoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderHistoryMousePressed
        btnOrderHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnOrderHistoryPressed.png")));
    }//GEN-LAST:event_btnOrderHistoryMousePressed

    private void btnOrderHistoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderHistoryMouseReleased
        btnOrderHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnOrderHistory.png")));
    }//GEN-LAST:event_btnOrderHistoryMouseReleased

    private void btnBackLedgerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLedgerMousePressed
        btnBackLedger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png")));
    }//GEN-LAST:event_btnBackLedgerMousePressed

    private void btnBackLedgerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLedgerMouseReleased
        btnBackLedger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png")));
    }//GEN-LAST:event_btnBackLedgerMouseReleased

    private void btnOrderHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderHistoryMouseClicked
        cardLayout.show(cardPanel, "cardLedger");
        List<Ledger> data = new ArrayList<>();
        try {
            data = LedgerDAO.getAllRecords();
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel model = (DefaultTableModel) tableLedger.getModel();
        for(int i= model.getRowCount() -1; i>=0; i--) {
            model.removeRow(i);
        }
        Object[] row = new Object[6];
        for(Ledger ledger: data) {
            row[0] = ledger.getId();
            row[1] = ledger.getName();
            row[2] = ledger.getEmail();
            row[3] = ledger.getAmt();
            Date d = ledger.getSchedule();
            SimpleDateFormat s1 = new SimpleDateFormat("dd-MM-yyyy");
            row[4] = s1.format(d);
            SimpleDateFormat s2 = new SimpleDateFormat("HH:mm:ss");
            row[5] = s2.format(d);
            model.addRow(row);
        }
    }//GEN-LAST:event_btnOrderHistoryMouseClicked

    private void btnBackLedgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLedgerMouseClicked
        cardLayout.show(cardPanel, "cardAdmin");
    }//GEN-LAST:event_btnBackLedgerMouseClicked

    private void btnBackMenuHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuHomeMousePressed
        btnBackMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png")));
    }//GEN-LAST:event_btnBackMenuHomeMousePressed

    private void btnBackMenuHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuHomeMouseReleased
        btnBackMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png")));
    }//GEN-LAST:event_btnBackMenuHomeMouseReleased

    private void btnBackMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuHomeMouseClicked
        cardLayout.show(cardPanel, "cardAdmin");
    }//GEN-LAST:event_btnBackMenuHomeMouseClicked

    private void btnPlaceOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlaceOrderMouseClicked
        cardLayout.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnPlaceOrderMouseClicked

    private void btnMenuHomeCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuHomeCartMouseClicked
        cardLayout.show(cardPanel, "cardCart");
        showProductsInCart();
    }//GEN-LAST:event_btnMenuHomeCartMouseClicked

    private void btnViewAllVegpizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllVegpizzaMouseClicked
        cardLayout.show(cardPanel, "cardMenuVeg");
    }//GEN-LAST:event_btnViewAllVegpizzaMouseClicked

    private void btnMenuVegCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuVegCartMouseClicked
        cardLayout.show(cardPanel, "cardCart");
        showProductsInCart();                        
    }//GEN-LAST:event_btnMenuVegCartMouseClicked

    private void btnViewAllNonVegPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllNonVegPizzaMouseClicked
        cardLayout.show(cardPanel, "cardMenuNonVeg");
    }//GEN-LAST:event_btnViewAllNonVegPizzaMouseClicked

    private void btnBackMenuNonVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuNonVegMouseClicked
        cardLayout.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnBackMenuNonVegMouseClicked

    private void btnBackMenuNonVegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuNonVegMousePressed
        btnBackMenuNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png")));
    }//GEN-LAST:event_btnBackMenuNonVegMousePressed

    private void btnBackMenuNonVegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuNonVegMouseReleased
        btnBackMenuNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png")));
    }//GEN-LAST:event_btnBackMenuNonVegMouseReleased

    private void btnBackMenuVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuVegMouseClicked
        cardLayout.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnBackMenuVegMouseClicked

    private void btnBackMenuVegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuVegMousePressed
        btnBackMenuVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png")));
    }//GEN-LAST:event_btnBackMenuVegMousePressed

    private void btnBackMenuVegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuVegMouseReleased
        btnBackMenuVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png")));
    }//GEN-LAST:event_btnBackMenuVegMouseReleased

    private void btnMenuNonVegCartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMenuNonVegCartKeyPressed
       
    }//GEN-LAST:event_btnMenuNonVegCartKeyPressed

    private void btnBackCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackCartMouseClicked
        cardLayout.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnBackCartMouseClicked

    private void btnBackCartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackCartMousePressed
        btnBackCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png")));
    }//GEN-LAST:event_btnBackCartMousePressed

    private void btnBackCartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackCartMouseReleased
        btnBackCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png")));
    }//GEN-LAST:event_btnBackCartMouseReleased

    private void btnMenuNonVegCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuNonVegCartMouseClicked
        cardLayout.show(cardPanel, "cardCart");
        showProductsInCart();
    }//GEN-LAST:event_btnMenuNonVegCartMouseClicked

    private void btnViewPizzaManiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewPizzaManiaMouseClicked
        cardLayout.show(cardPanel, "cardMenuManiaVeg");
    }//GEN-LAST:event_btnViewPizzaManiaMouseClicked

    private void btnBackMenuManiaVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuManiaVegMouseClicked
        cardLayout.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnBackMenuManiaVegMouseClicked

    private void btnBackMenuManiaVegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuManiaVegMousePressed
        btnBackMenuManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png")));
    }//GEN-LAST:event_btnBackMenuManiaVegMousePressed

    private void btnBackMenuManiaVegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuManiaVegMouseReleased
        btnBackMenuManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png")));
    }//GEN-LAST:event_btnBackMenuManiaVegMouseReleased

    private void btnMenuManiaVegCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuManiaVegCartMouseClicked
        cardLayout.show(cardPanel, "cardCart");
        showProductsInCart();
    }//GEN-LAST:event_btnMenuManiaVegCartMouseClicked

    private void btnMenuManiaNonVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuManiaNonVegMouseClicked
        cardLayout.show(cardPanel, "cardMenuManiaNonVeg");
        //btnMenuManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaNonVegPressed.png")));
        //btnMenuManiaVegPressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaVeg.png")));
    }//GEN-LAST:event_btnMenuManiaNonVegMouseClicked

    private void btnMenuManiaVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuManiaVegMouseClicked
        cardLayout.show(cardPanel, "cardMenuManiaVeg");
        //btnMenuManiaNonVegPressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaNonVeg.png")));
        //btnMenuManiaVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txtPizzaManiaVegPressed.png")));
    }//GEN-LAST:event_btnMenuManiaVegMouseClicked

    private void btnBackMenuManiaNonVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuManiaNonVegMouseClicked
        cardLayout.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnBackMenuManiaNonVegMouseClicked

    private void btnBackMenuManiaNonVegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuManiaNonVegMousePressed
        btnBackMenuManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png")));
    }//GEN-LAST:event_btnBackMenuManiaNonVegMousePressed

    private void btnBackMenuManiaNonVegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuManiaNonVegMouseReleased
        btnBackMenuManiaNonVeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png")));
    }//GEN-LAST:event_btnBackMenuManiaNonVegMouseReleased

    private void btnAllBeveragesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAllBeveragesMouseClicked
        cardLayout.show(cardPanel, "cardMenuBeverages");
    }//GEN-LAST:event_btnAllBeveragesMouseClicked

    private void btnBackMenuBeveragesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuBeveragesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMenuBeveragesMouseEntered

    private void btnBackMenuBeveragesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuBeveragesMouseClicked
        cardLayout.show(cardPanel, "cardMenuHome");
    }//GEN-LAST:event_btnBackMenuBeveragesMouseClicked

    private void btnBackMenuBeveragesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuBeveragesMousePressed
        btnBackMenuBeverages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png")));
    }//GEN-LAST:event_btnBackMenuBeveragesMousePressed

    private void btnBackMenuBeveragesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuBeveragesMouseReleased
        btnBackMenuBeverages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png")));
    }//GEN-LAST:event_btnBackMenuBeveragesMouseReleased

    private void btnMenuBeverageCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuBeverageCartMouseClicked
        cardLayout.show(cardPanel, "cardCart");
        showProductsInCart();
    }//GEN-LAST:event_btnMenuBeverageCartMouseClicked

    private void btnproceedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproceedMouseClicked
        cardLayout.show(cardPanel, "cardPayment");
        lblPaymentTotal.setText(Double.toString(totalAmt));
        lblGST.setText(Double.toString((totalAmt*5)/100));
        lblAmountPayable.setText(Double.toString(totalAmt+(totalAmt*5)/100));
        Date d = new Date(); 
         SimpleDateFormat s1 = new SimpleDateFormat("dd-MM-yyyy");
            lblDate.setText(s1.format(d));
            SimpleDateFormat s2 = new SimpleDateFormat("HH:mm:ss");
            lblTime.setText(s2.format(d));
    }//GEN-LAST:event_btnproceedMouseClicked

    private void btnBackPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPaymentMouseClicked
        cardLayout.show(cardPanel, "cardCart");
    }//GEN-LAST:event_btnBackPaymentMouseClicked

    private void btnBackPaymentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPaymentMousePressed
        btnBackPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBackPressed.png")));
    }//GEN-LAST:event_btnBackPaymentMousePressed

    private void btnBackPaymentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPaymentMouseReleased
       btnBackPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnBack.png")));
    }//GEN-LAST:event_btnBackPaymentMouseReleased

    private void v01KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_v01KeyPressed
      
    }//GEN-LAST:event_v01KeyPressed

    private void v01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v01MouseClicked
        addProduct("v01");
        cartData.forEach(e -> System.out.println(e.toString()));
    }//GEN-LAST:event_v01MouseClicked

    private void v02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v02MouseClicked
        addProduct("v02");
    }//GEN-LAST:event_v02MouseClicked

    private void v03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v03MouseClicked
        addProduct("v03");
    }//GEN-LAST:event_v03MouseClicked

    private void v04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v04MouseClicked
        addProduct("v04");
    }//GEN-LAST:event_v04MouseClicked

    private void v05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v05MouseClicked
        addProduct("v05");
    }//GEN-LAST:event_v05MouseClicked

    private void v06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v06MouseClicked
        addProduct("v0");
    }//GEN-LAST:event_v06MouseClicked

    private void v07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v07MouseClicked
        addProduct("v07");
    }//GEN-LAST:event_v07MouseClicked

    private void v08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v08MouseClicked
        addProduct("v08");
    }//GEN-LAST:event_v08MouseClicked

    private void nv01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv01MouseClicked
        addProduct("nv01");
    }//GEN-LAST:event_nv01MouseClicked

    private void nv02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv02MouseClicked
        addProduct("nv02");
    }//GEN-LAST:event_nv02MouseClicked

    private void nv03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv03MouseClicked
        addProduct("nv03");
    }//GEN-LAST:event_nv03MouseClicked

    private void nv04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv04MouseClicked
        addProduct("nv04");
    }//GEN-LAST:event_nv04MouseClicked

    private void nv05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv05MouseClicked
        addProduct("nv05");
    }//GEN-LAST:event_nv05MouseClicked

    private void nv06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv06MouseClicked
        addProduct("nv06");
    }//GEN-LAST:event_nv06MouseClicked

    private void nv07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv07MouseClicked
        addProduct("nv07");
    }//GEN-LAST:event_nv07MouseClicked

    private void nv08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nv08MouseClicked
        addProduct("nv08");
    }//GEN-LAST:event_nv08MouseClicked

    private void mv01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv01MouseClicked
        addProduct("mv01");
    }//GEN-LAST:event_mv01MouseClicked

    private void mv02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv02MouseClicked
        addProduct("mv02");
    }//GEN-LAST:event_mv02MouseClicked

    private void mv03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv03MouseClicked
        addProduct("mv03");
    }//GEN-LAST:event_mv03MouseClicked

    private void mv04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv04MouseClicked
        addProduct("mv04");
    }//GEN-LAST:event_mv04MouseClicked

    private void mv05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv05MouseClicked
        addProduct("mv05");
    }//GEN-LAST:event_mv05MouseClicked

    private void mv06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv06MouseClicked
        addProduct("mv06");
    }//GEN-LAST:event_mv06MouseClicked

    private void mv07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv07MouseClicked
        addProduct("mv07");
    }//GEN-LAST:event_mv07MouseClicked

    private void mv08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mv08MouseClicked
        addProduct("mv08");
    }//GEN-LAST:event_mv08MouseClicked

    private void mnv01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnv01MouseClicked
        addProduct("mnv01");
    }//GEN-LAST:event_mnv01MouseClicked

    private void mnv02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnv02MouseClicked
        addProduct("mnv02");
    }//GEN-LAST:event_mnv02MouseClicked

    private void mnv03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnv03MouseClicked
        addProduct("mnv03");
    }//GEN-LAST:event_mnv03MouseClicked

    private void b01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b01MouseClicked
        addProduct("b01");
    }//GEN-LAST:event_b01MouseClicked

    private void b02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b02MouseClicked
        addProduct("b02");
    }//GEN-LAST:event_b02MouseClicked

    private void b03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b03MouseClicked
        addProduct("b03");
    }//GEN-LAST:event_b03MouseClicked

    private void b04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b04MouseClicked
        addProduct("b04");
    }//GEN-LAST:event_b04MouseClicked

    private void b05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b05MouseClicked
        addProduct("b05");
    }//GEN-LAST:event_b05MouseClicked

    private void b06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b06MouseClicked
        addProduct("b06");
    }//GEN-LAST:event_b06MouseClicked

    private void b07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b07MouseClicked
        addProduct("b07");
    }//GEN-LAST:event_b07MouseClicked

    private void btnMenuManiaNonVegCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuManiaNonVegCartMouseClicked
        cardLayout.show(cardPanel, "cardCart");
        showProductsInCart();
    }//GEN-LAST:event_btnMenuManiaNonVegCartMouseClicked

    private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseClicked
        int row = tableCart.getSelectedRow();
        cartData.remove(row);
        totalAmt = 0;
        showProductsInCart();
    }//GEN-LAST:event_btnRemoveMouseClicked

    private void btnSendReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendReceiptMouseClicked
        if(txtUsername.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Dear please enter username");
        }else if(!isValidEmail(txtEmail.getText())){
            JOptionPane.showConfirmDialog(null, "Dear please enter valid Email");
        }else{
            Ledger ledger = new Ledger(0, txtUsername.getText(), txtEmail.getText(), (totalAmt+(totalAmt*5)/100), null);
            try { 
                LedgerDAO.saveRocerd(ledger);
                sendMail(txtUsername.getText(), txtEmail.getText(), (totalAmt +(totalAmt*5)/100));
                cardLayout.show(cardPanel, "cardMenuHome");
                totalAmt = 0.0;
                cartCount = 0;
                cartData.clear();
                setCartCount();
                
            } catch (SQLException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSendReceiptMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin;
    private javax.swing.JLabel b01;
    private javax.swing.JLabel b02;
    private javax.swing.JLabel b03;
    private javax.swing.JLabel b04;
    private javax.swing.JLabel b05;
    private javax.swing.JLabel b06;
    private javax.swing.JLabel b07;
    private javax.swing.JLabel bgAdmin;
    private javax.swing.JLabel bgCart;
    private javax.swing.JLabel bgCart1;
    private javax.swing.JLabel bgLedger;
    private javax.swing.JLabel bgMenuBeverages;
    private javax.swing.JLabel bgMenuHome;
    private javax.swing.JLabel bgMenuManiaNonVeg;
    private javax.swing.JLabel bgMenuManiaVeg;
    private javax.swing.JLabel bgMenuNonVeg;
    private javax.swing.JLabel bgMenuVeg;
    private javax.swing.JLabel btnAllBeverages;
    private javax.swing.JLabel btnBackCart;
    private javax.swing.JLabel btnBackLedger;
    private javax.swing.JLabel btnBackMenuBeverages;
    private javax.swing.JLabel btnBackMenuHome;
    private javax.swing.JLabel btnBackMenuManiaNonVeg;
    private javax.swing.JLabel btnBackMenuManiaVeg;
    private javax.swing.JLabel btnBackMenuNonVeg;
    private javax.swing.JLabel btnBackMenuVeg;
    private javax.swing.JLabel btnBackPayment;
    private javax.swing.JLabel btnMenNonVegCartCount;
    private javax.swing.JLabel btnMenuBeverageCart;
    private javax.swing.JLabel btnMenuBeverageCartCount;
    private javax.swing.JLabel btnMenuHomeCart;
    private javax.swing.JLabel btnMenuHomeCartCount;
    private javax.swing.JLabel btnMenuManiaNonVeg;
    private javax.swing.JLabel btnMenuManiaNonVegCart;
    private javax.swing.JLabel btnMenuManiaNonVegCartCount;
    private javax.swing.JLabel btnMenuManiaNonVegPressed;
    private javax.swing.JLabel btnMenuManiaVeg;
    private javax.swing.JLabel btnMenuManiaVegCart;
    private javax.swing.JLabel btnMenuManiaVegCartCount;
    private javax.swing.JLabel btnMenuManiaVegPressed;
    private javax.swing.JLabel btnMenuNonVegCart;
    private javax.swing.JLabel btnMenuVegCart;
    private javax.swing.JLabel btnMenuVegCartCount;
    private javax.swing.JLabel btnOrderHistory;
    private javax.swing.JLabel btnPlaceOrder;
    private javax.swing.JLabel btnRemove;
    private javax.swing.JLabel btnSendReceipt;
    private javax.swing.JLabel btnViewAllNonVegPizza;
    private javax.swing.JLabel btnViewAllVegpizza;
    private javax.swing.JLabel btnViewPizzaMania;
    private javax.swing.JLabel btnproceed;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel cart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAmountPayable;
    private javax.swing.JLabel lblCartTotal;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblGST;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblPaymentTotal;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel ledger;
    private javax.swing.JPanel menuBeverages;
    private javax.swing.JPanel menuHome;
    private javax.swing.JPanel menuManiaNonVeg;
    private javax.swing.JPanel menuManiaVeg;
    private javax.swing.JPanel menuNonVeg;
    private javax.swing.JPanel menuVeg;
    private javax.swing.JLabel mnv01;
    private javax.swing.JLabel mnv02;
    private javax.swing.JLabel mnv03;
    private javax.swing.JLabel mv01;
    private javax.swing.JLabel mv02;
    private javax.swing.JLabel mv03;
    private javax.swing.JLabel mv04;
    private javax.swing.JLabel mv05;
    private javax.swing.JLabel mv06;
    private javax.swing.JLabel mv07;
    private javax.swing.JLabel mv08;
    private javax.swing.JLabel nv01;
    private javax.swing.JLabel nv02;
    private javax.swing.JLabel nv03;
    private javax.swing.JLabel nv04;
    private javax.swing.JLabel nv05;
    private javax.swing.JLabel nv06;
    private javax.swing.JLabel nv07;
    private javax.swing.JLabel nv08;
    private javax.swing.JPanel payment;
    private javax.swing.JTable tableCart;
    private javax.swing.JTable tableLedger;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel v01;
    private javax.swing.JLabel v02;
    private javax.swing.JLabel v03;
    private javax.swing.JLabel v04;
    private javax.swing.JLabel v05;
    private javax.swing.JLabel v06;
    private javax.swing.JLabel v07;
    private javax.swing.JLabel v08;
    // End of variables declaration//GEN-END:variables
    private void addProduct(String prodId) {
        try {
            cartData.add(ProductDAO.findProductByProdId(prodId));
            cartCount = cartData.size();
            setCartCount();
            
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setCartCount() {
            btnMenuHomeCartCount.setText(Integer.toString(cartCount));
            btnMenuVegCartCount.setText(Integer.toString(cartCount));
            btnMenNonVegCartCount.setText(Integer.toString(cartCount));
            btnMenuManiaVegCartCount.setText(Integer.toString(cartCount));
            btnMenuManiaNonVegCartCount.setText(Integer.toString(cartCount));
            btnMenuBeverageCartCount.setText(Integer.toString(cartCount));
    }
    private void showProductsInCart(){
         DefaultTableModel model = (DefaultTableModel) tableCart.getModel();
        for(int i= model.getRowCount() -1; i >=0; i--) {
            model.removeRow(i);
        }
        Object[] row = new Object[2];
        for(Product product : cartData) {
            row[0] = product.getProdName();
            row[1] = product.getAmt();
            totalAmt += product.getAmt();
            model.addRow(row);
        }
        lblCartTotal.setText(Double.toString(totalAmt));
    }
    public static boolean isValidEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."
                + "[a-zA-Z0-9_+&*-]+)*@"
                + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
                + "A-Z]{2,7}$";
        Pattern pat = Pattern.compile(emailRegex);
        if(email == null) {
            return false;
        }
        return pat.matcher(email).matches();
    }
    public void sendMail(String name, String email, double amt) {
            String to = email;
            
            String from = "sachinkhapariye.05@gmail.com";
            
            String host = "smtp.gmail.com";
            Properties properties = System.getProperties();
            
            properties.put("mail.smtp.host",host);
            properties.put("mail.smtp.port", "465");
            properties.put("mail.smtp.ssl.enable", "true");
            properties.put("mail.smtp.auth","true");
            
            Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
                
                protected PasswordAuthentication getPasswordAuthentication(){
                    return new PasswordAuthentication("sachinkhapariye.05@gmail.com", "$$$$280103");
                    
                }
            });
            session.setDebug(true);
            try{
                MimeMessage message = new MimeMessage(session);
                message.setFrom(new InternetAddress(from));
                message.addRecipient(Message.RecipientType.TO,new InternetAddress(to));
                message.setSubject("Labrai");
                message.setContent("<h1>Hello" + name + " your order has been successfully. Total amount is Rs." + amt + "</h1>","text/html;charset=utf-8");
                System.out.println("Sending...");
                Transport.send(message);
                System.out.println("Sent message successfully...");
            }catch (MessagingException mex){
                mex.printStackTrace();
            }
    }
}
